# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AutographaGo_ReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AutographaGo_ReactNative
  pod 'Firebase/Core'

  target 'AutographaGo_ReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNFS', :path => '../node_modules/react-native-fs'

  end

  target 'AutographaGo_ReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AutographaGo_ReactNative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AutographaGo_ReactNative-tvOS

end
