# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AutographaGo_ReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AutographaGo_ReactNative
  pod 'Firebase/Core'

  target 'AutographaGo_ReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNFS', :path => '../node_modules/react-native-fs'

    pod 'RNSound', :path => '../node_modules/react-native-sound'

    pod 'react-native-video', :path => '../node_modules/react-native-video'

    pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

    pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

    pod 'RNScreens', :path => '../node_modules/react-native-screens'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

    pod 'toolbar-android', :path => '../node_modules/@react-native-community/toolbar-android'

    pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  end

  target 'AutographaGo_ReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AutographaGo_ReactNative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AutographaGo_ReactNative-tvOS

end
